# Generated by Django 4.2 on 2025-06-08 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите назваине породы', max_length=128, verbose_name='Порода')),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], help_text='Выбирете размер собаки', max_length=20, verbose_name='Размер собаки')),
                ('friendliness', models.PositiveSmallIntegerField(help_text='Укажите уровень дружелюбия от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Дружелюбие')),
                ('trainability', models.PositiveSmallIntegerField(help_text='Укажите уровень обучаемости от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Обучаемость')),
                ('shedding_amount', models.PositiveSmallIntegerField(help_text='Укажите количество линьки от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество линьки')),
                ('exercise_needs', models.PositiveSmallIntegerField(help_text='Укажите длительность физической активности 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Физическая активность')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя собаки', max_length=128, verbose_name='Имя собаки')),
                ('age', models.PositiveSmallIntegerField(help_text='Укажите возраст собаки от 0 до 20 лет', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Возраст собаки')),
                ('gender', models.CharField(choices=[('Самец', 'Самец'), ('Самка', 'Самка')], help_text='Выберите пол собаки', max_length=20, verbose_name='Пол собаки')),
                ('color', models.CharField(help_text='Укажите цвет собаки', max_length=255, verbose_name='Цвет собаки')),
                ('favorite_food', models.CharField(help_text='Укажите любимую еду', max_length=255, verbose_name='Любимая еда')),
                ('favorite_toy', models.CharField(help_text='Укажите любимую игрушку', max_length=255, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(help_text='Укажите породу собаки', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.breed')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['-id'],
            },
        ),
    ]
