# Generated by Django 4.2 on 2025-06-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('-id',), 'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('-id',), 'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(help_text='Укажите породу собаки', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.breed', verbose_name='Порода'),
        ),
    ]
